<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Api\Financas\Patrimonio.Financas.Contracts\Patrimonio.Financas.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Cartoes\Navigation\LancamentoNavigationView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Cartoes\Navigation\FaturaNavigationView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Cartoes\Navigation\CartaoNavigationView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Cartoes\Views\FaturaPagamentoView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Cartoes\Views\LancamentoFormView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Cartoes\Views\FaturaFormView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Cartoes\Views\CartaoFormView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Cartoes\Views\LancamentoListaView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Cartoes\Views\FaturaListaView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Cartoes\Views\CartaoListaView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Categorias\Views\CategoriaFormView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Contas\Navigation\ContaNavigationView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Instituicoes\Navigation\InstituicaoNavigationView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Instituicoes\Views\InstituicaoFormView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Instituicoes\Views\InstituicaoListaView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Movimentacoes\Navigation\MovimentacaoNavigationView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

</Project>
